import type { Metadata } from "next";
import "./globals.css";
import ProtecteRouting from "./ProtecteRouting";
import {Poppins} from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "700", "900", "800", "600"],
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased h-screen bg-slate-100 overflow-hidden`}
      >
        <ProtecteRouting>
          {children}
        </ProtecteRouting>
      </body>
    </html>
  );
}
